### PR TITLE
Add webpack 3 peerDependency, upgrade to webpack 3

### PR DESCRIPTION
**Pull request by nkovacs**
Seems to work fine, make test and make integration-test pass.

[There aren't a lot of breaking changes](https://github.com/webpack/webpack/releases/tag/v3.0.0).

### CODE REVIEW

**Comment by plasticine** [comment]
Nice, thanks — will have a look and see if we can't get this shipped. :)

**Comment by plasticine** [comment]
Thanks! :)

**Comment by bastimeyer** [comment]
Could you please bump the version and publish a new release with this change? Thanks!

**Comment by txchen** [comment]
@plasticine would you please release a new version with this? Vuejs users are waiting for webpack 3 templates:) Thanks a lot!

**Pull request merged**
