### PR TITLE
Merge injectify-loader and inject-loader

### LINKED ISSUE #32: $' combination breaks parsing
Hello,

I've noticed that inject-loader cannot correctly process `$'` combination in files.

Given the following code:
```javascript
define(function (require) {
    'use strict';

    var _ = require('lodash');
    var regexp = new RegExp('^(one|two|three)$', 'i');

    return {
        getRegex: _.constant(regexp)
    };
});

```

I've got the following output:
```javascript
module.exports = function __injectWrapper() {
    var __injections = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};

    var module = { exports: {} };
    var exports = module.exports;

    // $FlowIgnore
    var __wrappedModuleDependencies = ["lodash"];

    (function __validateInjection() {
      var injectionKeys = Object.keys(__injections);
      var invalidInjectionKeys = injectionKeys.filter(function (x) {
        return __wrappedModuleDependencies.indexOf(x) === -1;
      });

      if (invalidInjectionKeys.length > 0) throw new Error('One or more of the injections you passed in is invalid for the module you are attempting to inject into.\n\n- Valid injection targets for this module are: ' + __wrappedModuleDependencies.join(' ') + '\n- The following injections were passed in:     ' + injectionKeys.join(' ') + '\n- The following injections are invalid:        ' + invalidInjectionKeys.join(' ') + '\n');
    })();

    function __injection(dependency) {
      return __injections.hasOwnProperty(dependency) ? __injections[dependency] : null;
    }

    /*!************************************************************************/
    (function () {
      // $FlowIgnore
      'use strict';

define(function (require) {
    'use strict';

    var _ = (__injection("lodash") || require("lodash"));
    var regexp = new RegExp('^(one|two|three)
    })();
    /*!************************************************************************/

    return module.exports;
  }, 'i');

    return {
        getRegex: _.constant(regexp)
    };
});
    })();
    /*!************************************************************************/

    return module.exports;
  }
```

This part is broken:
```javascript
    var regexp = new RegExp('^(one|two|three)
    })();
```

Any questions - please let me know.
P.s. And many thanks for this package, it's a real life-saver for me :+1:

### PR DESCRIPTION
**Pull request by vladimir-tikhonov**
Fixes #32

I've removed `flow` typings because I'm not familiar with flow and don't think that it will help much on such small project. Hovewer I can try to add them back if you want.
Feel free to ask any questions or request changes.

### CODE REVIEW

**Comment by vladimir-tikhonov** [comment]
I've added additional test in https://github.com/plasticine/inject-loader/pull/36/commits/2cf7b6ec1ff783dc401efb431fb4572ee8170f49  to ensure that we don't break `obj.require()` calls. cc @rmp135

**Comment by vladimir-tikhonov** [comment]
Commit https://github.com/plasticine/inject-loader/pull/36/commits/e7dc6f92e916256acdc669a65c2446b60a60dec1 adds sourcemaps support (fixes #10 )

**Comment by plasticine** [comment]
@vladimir-tikhonov This is phenomenal stuff — great work, huge effort! 👏 

I’ve made a few really minor tweaks to some of the tooling and example code, but the actual library code is perfect! 👌 

If you’re happy then let’s ship this and release it as `3.0`.

**Comment by plasticine** [comment]
@vladimir-tikhonov apologies for the few broken commits there, looks like there were a few issues with the example/integration tests.

**Comment by vladimir-tikhonov** [comment]
Good catches, @plasticine 👍

**Pull request merged**
