### PR TITLE
Expose exports variable to support CommonJS and Babel

### PR DESCRIPTION
**Pull request by ErrorPro**

### CODE REVIEW

**Comment by ErrorPro** [comment]
This PR could fix this issue #6

**Comment by nkbt** [comment]
@ErrorPro that fixes #6 for sure, see comment https://github.com/plasticine/inject-loader/issues/6#issuecomment-124474515

**Comment by plasticine** [comment]
Hey peeps :)

I'm on vacation for the next week or so, will merge and sort out a bunch of these when I get back to work. :v:

**Comment by plasticine** [comment]
Ok, seems people really want this fix, so I will put it into master as I can't see any reason not to. However I can only eyeball the code as I am sans-computer for the next week, this also means there will be not new release published until I am back at a keyboard—people will have to use master.

**Comment by nkbt** [comment]
Great, thanks!

**Pull request merged**
