### PR TITLE
General refactor

### PR DESCRIPTION
**Pull request by rmp135**
I initially went to fix a bug with inject-loader breaking methods that were named "require" (e.g. electron.require("...")) and one thing led to another...

Anyway, the codebase can be tested in a much cleaner way with a lot less plumbing between the various parts. The tests have been fleshed out and unnecessary dependencies trimmed. 
The original webpack1 and webpack2 integration tests are still in place and pass.

### CODE REVIEW

**Comment by plasticine** [comment]
@rmp135 Hey mate — thanks for the PR! Have given it a quick look over, looks like a really nice little cleanup! :)

Will try and find some time to pull it down properly and have a look in more detail today.

**Comment by rmp135** [comment]
What's the status on this?

**Comment by plasticine** [comment]
@rmp135 Sorry — I’ve been AFK for a bit and have not got around to it yet.

**Comment by vladimir-tikhonov** [comment]
@rmp135 seems like everything you've done here is covered by #36. I'll close this pull request, but feel free to re-open it if I missed something.

**Pull request closed without merging**
